name: pygraf
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - basemap
  - basemap-data-hires
  - pynio=1.5.5
  - notebook
  - matplotlib
  - metpy=0.12.1
  - numpy=1.21.*
  - pint=0.10.*
  - pylint
  - pytest
  - pyyaml
  - setuptools=59.8.*
  - xarray=0.15*
  - dask
