name: graphics_tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test_graphics:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          lfs: true
      - name: Install Miniforge with pygraf environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          miniforge-version: latest
          cache-downloads: true
          cache-environment: true
      - name: Install dev pkgs
        run: make devenv
      - name: Lint code
        run: make lint
      - name: Test code
        run: make test
