name: hrrr_maps_tests
env: 
  DATA_LOC: ${{ github.workspace }}/input_data
  OUTPUT_LOC: ${{ github.workspace }}/output
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test_hrrr_maps:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Create data and output folders
        run: |
          mkdir -p $OUTPUT_LOC
          mkdir -p $DATA_LOC
      - name: Fetch Grib Files
        run: |
          wget -N -P $DATA_LOC -i - << EOF
          https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrrr.20230315/conus/hrrr.t00z.wrfprsf00.grib2
          https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrrr.20230315/conus/hrrr.t00z.wrfprsf01.grib2
          https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrrr.20230315/conus/hrrr.t00z.wrfprsf02.grib2
          https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrrr.20230315/conus/hrrr.t00z.wrfprsf03.grib2
          https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrrr.20230315/conus/hrrr.t00z.wrfprsf04.grib2
          https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrrr.20230315/conus/hrrr.t00z.wrfprsf05.grib2
          https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrrr.20230315/conus/hrrr.t00z.wrfprsf06.grib2
          EOF
          ls
      - name: Install Miniforge with pygraf environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          miniforge-version: latest
      - name: Install dev pkgs
        run: make devenv
      - name: Test code
        run: |
          export GITHUB_WORKSPACE=$(pwd)
          conda activate pygraf
          pytest -vv tests/test_hrrr_maps.py
        shell: bash -el {0}
